# Workflow name
name: 'Chromatic'

# Events for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# List of jobs
jobs:
  chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.0'
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: bun install
      - run: bun run build
      #👇 Chromatic check for pull requests
      - name: Chromatic PR Check
        if: github.event_name == 'pull_request'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exitOnceUploaded: true
      #👇 Chromatic publish when main is updated
      - name: Chromatic Publish
        if: github.event_name == 'push'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: true
          exitOnceUploaded: true
